### ISSUE TITLE
inconsistent READSB/DUMP978 env setup

### ISSUE THREAD

**Issue by tedder** [mikenye/docker-dump978#17]
The [documented environment variables](https://github.com/mikenye/docker-dump978/blob/d2dfd3ee3418268a73a7e66133000ef937376370/README.md#environment-variables) are all namespaced as "DUMP978*". But 02-sanity-check looks at `READSB_DEVICE_TYPE` and `READSB_RTLSDR_DEVICE`. 05-rtlsdr-biastee does similar.

However, the `run` file (at `etc/services.d/dump978/run`) uses the DUMP978 namespace.

So, both are required. Or at least they are when there are multiple dongles plugged in:
```
[cont-init.d] 02-sanity-check: executing... 
ERROR: Multiple RTL-SDR devices present. Please set READSB_RTLSDR_DEVICE!
[cont-init.d] 02-sanity-check: exited 1.
```

I'm hanging out in discord if you wanna chat there.

**Comment by mikenye** [comment]
This should now be fixed.
