### ISSUE TITLE
Possible to add support for the Stratux UAT v3 radio?

### ISSUE THREAD

**Issue by mooscomputer** [mikenye/docker-dump978#20]
Would it be possible to implement the stratuxv3 option in this container?
"--stratuxv3 arg           read messages from Stratux v3 UAT dongle on given serial port"

On my RPi 3B here is the output of the serial devices with the startux v3 UAT radio attached

```
pi@raspberrypi:/opt/adsb $ dmesg | grep tty
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=Composite-1:720x480@60i vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=22117965-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    0.001175] printk: console [tty1] enabled
[    3.274697] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 99, base_baud = 0) is a PL011 rev2
[    5.739702] systemd[1]: Created slice system-getty.slice.
[    7.719500] cdc_acm 1-1.2:1.0: ttyACM0: USB ACM device
```

I think from the output here that the ttyACM0 device is the stratux radio.

Stratux radio is based off TI CC1310.

Thanks

**Comment by mikenye** [comment]
Hi @mooscomputer,

I've hopefully implemented this in branch issue_20.

Are you able to clone that repo, build the container and test (as I don't own this radio, and there's no UAT in Australia either...).

To do this:

```bash
git clone https://github.com/mikenye/docker-dump978.git /tmp/docker-dump978
pushd /tmp/docker-dump978
docker build -t dump978 .
popd
```

Then you can launch the container (make sure nothing else is using that device first) with the command:

```bash
docker run \
    -d \
    --restart=always \
    -it \
    --name dump978 \
    -p 30978:30978 \
    -p 30979:30979 \
    -p 37981:37981 \
    --device /dev/ttyAMA0:/dev/ttyAMA0 \
    -e DUMP978_DEVICE_TYPE=stratuxv3 \
    -e DUMP978_STRATUXV3_DEVICE=/dev/ttyAMA0 \
   dump978
```

You can view the container logs with `docker logs -f dump978`.

Let me know how you go!

Thanks.

**Comment by mooscomputer** [comment]
When executing the build sequence it errors out with the follwoing:

g++ -std=c++11 -Wall -Wno-psabi -Werror -O2 -g -Ilibs -DVERSION=\"c1e37f4\"  -c -o dump978_main.o dump978_main.cc
g++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
make: *** [<builtin>: dump978_main.o] Error 1
The command '/bin/bash -o pipefail -c set -x &&     TEMP_PACKAGES=() &&     KEPT_PACKAGES=() &&     TEMP_PACKAGES+=(build-essential) &&     TEMP_PACKAGES+=(ca-certificates) &&     TEMP_PACKAGES+=(cmake) &&     TEMP_PACKAGES+=(curl) &&     TEMP_PACKAGES+=(git) &&     KEPT_PACKAGES+=(gawk) &&     TEMP_PACKAGES+=(gnupg2) &&     TEMP_PACKAGES+=(file) &&     TEMP_PACKAGES+=(libusb-1.0-0-dev) &&     KEPT_PACKAGES+=(libusb-1.0-0) &&     TEMP_PACKAGES+=(pkg-config) &&     TEMP_PACKAGES+=(libboost-dev) &&     TEMP_PACKAGES+=(libboost-system1.67-dev) &&     KEPT_PACKAGES+=(libboost-system1.67.0) &&     TEMP_PACKAGES+=(libboost-program-options1.67-dev) &&     KEPT_PACKAGES+=(libboost-program-options1.67.0) &&     TEMP_PACKAGES+=(libboost-regex1.67-dev) &&     KEPT_PACKAGES+=(libboost-regex1.67.0) &&     TEMP_PACKAGES+=(libboost-filesystem1.67-dev) &&     KEPT_PACKAGES+=(libboost-filesystem1.67.0) &&     KEPT_PACKAGES+=(socat) &&     TEMP_PACKAGES+=(apt-transport-https) &&     KEPT_PACKAGES+=(net-tools) &&     KEPT_PACKAGES+=(jq) &&     apt-get update &&     apt-get install -y --no-install-recommends         ${KEPT_PACKAGES[@]}         ${TEMP_PACKAGES[@]}         &&     git config --global advice.detachedHead false &&     git clone "${URL_REPO_RTLSDR}" "/src/rtl-sdr" &&     pushd "/src/rtl-sdr" &&     git checkout "${BRANCH_RTLSDR}" &&     echo "rtl-sdr ${BRANCH_RTLSDR}" >> /VERSIONS &&     mkdir -p "/src/rtl-sdr/build" &&     pushd "/src/rtl-sdr/build" &&     cmake ../ -DINSTALL_UDEV_RULES=ON -Wno-dev -DCMAKE_BUILD_TYPE=Release &&     make -Wstringop-truncation &&     make -Wstringop-truncation install &&     cp -v "/src/rtl-sdr/rtl-sdr.rules" "/etc/udev/rules.d/" &&     ldconfig &&     popd && popd &&     git clone "${URL_REPO_SOAPYSDR}" "/src/SoapySDR" &&     pushd "/src/SoapySDR" &&     BRANCH_SOAPYSDR=$(git tag --sort="-creatordate" | head -1) &&     git checkout "${BRANCH_SOAPYSDR}" &&     mkdir -p "/src/SoapySDR/build" &&     pushd "/src/SoapySDR/build" &&     cmake ../ -DCMAKE_BUILD_TYPE=Release &&     make &&     make test &&     make install &&     ldconfig &&     echo "SoapySDR $(SoapySDRUtil --info | grep -i 'lib version:' | cut -d ':' -f 2 | tr -d ' ')" >> /VERSIONS &&     popd && popd &&     git clone "${URL_REPO_SOAPYRTLSDR}" "/src/SoapyRTLSDR" &&     pushd "/src/SoapyRTLSDR" &&     BRANCH_SOAPYRTLSDR=$(git tag --sort="-creatordate" | head -1) &&     git checkout "${BRANCH_SOAPYRTLSDR}" &&     echo "SoapyRTLSDR ${BRANCH_SOAPYRTLSDR}" >> /VERSIONS &&     mkdir -p "/src/SoapyRTLSDR/build" &&     pushd "/src/SoapyRTLSDR/build" &&     cmake ../ -DCMAKE_BUILD_TYPE=Release &&     make &&     make install &&     popd && popd &&     git clone "${URL_REPO_DUMP978}" "/src/dump978" &&     pushd "/src/dump978" &&     BRANCH_DUMP978=$(git tag --sort="-creatordate" | head -1) &&     git checkout "${BRANCH_DUMP978}" &&     make all faup978 &&     mkdir -p "/usr/lib/piaware/helpers" &&     cp -v dump978-fa skyaware978 "/usr/local/bin/" &&     cp -v faup978 "/usr/lib/piaware/helpers/" &&     mkdir -p "/usr/share/dump978-fa/html" &&     cp -a "/src/dump978/skyaware/"* "/usr/share/dump978-fa/html/" &&     popd &&     git clone "${URL_REPO_UAT2ESNT}" "/src/uat2esnt" &&     pushd "/src/uat2esnt" &&     git checkout "1992abdcb409d1c5e23139fd993bb1c81c349abd" &&     make all test &&     cp -v ./uat2text /usr/local/bin/ &&     cp -v ./uat2esnt /usr/local/bin/ &&     cp -v ./uat2json /usr/local/bin/ &&     cp -v ./extract_nexrad /usr/local/bin/ &&     mkdir -p /run/uat2json &&     popd &&     curl --location --silent -o - https://repos.influxdata.com/influxdb.key | apt-key add - &&     source /etc/os-release &&     echo "deb https://repos.influxdata.com/debian $VERSION_CODENAME stable" > /etc/apt/sources.list.d/influxdb.list &&     apt-get update &&     apt-get install --no-install-recommends -y telegraf &&     curl -s https://raw.githubusercontent.com/mikenye/deploy-s6-overlay/master/deploy-s6-overlay.sh | sh &&     apt-get remove -y ${TEMP_PACKAGES[@]} &&     apt-get autoremove -y &&     rm -rf /src/* /tmp/* /var/lib/apt/lists/* &&     ( dump978-fa --version > /VERSIONS 2>&1 || true ) &&     grep dump978 /VERSIONS | cut -d ' ' -f2 >> /CONTAINER_VERSION &&     cat /VERSIONS &&     cat /CONTAINER_VERSION' returned a non-zero code: 2

**Comment by mooscomputer** [comment]
@mikenye I will try to rerun the build sequence per your instructions again.  I will try it with the containers down to allow for max resource availability.

**Comment by mooscomputer** [comment]
@mikenye Here is the full output of the docker build command. still no luck

https://pastebin.com/AAZU9RWE

**Comment by mooscomputer** [comment]
@mikenye confimed stratuxv3 options working after your latest build on a pi3b. Thanks for your time and hard work.
